site_info:
  client_id: "invincible_ocean"
  site_name: "head_office"
  country: "india"
  state: "gujarat"
  district: "ahmedabad"
  site_id: "ro001"
  latitude: 22.98
  longitude: 72.47

cloud_storage:
  bucket_name: "roboi-event-captures"

models:
  primary: "models/exports/yolo11n.pt"
  fire: "models/exports/yolo11n_fire.pt"
  fight: "models/exports/yolo8n_fight.pt"

analytics:
  heartbeat_interval: 60.0
  alert_cooldown: 120.0
  snapshots_per_event: 3
  pre_event_seconds: 3
  post_event_seconds: 5
  face_recognition_threshold: 0.30
  face_detection_threshold: 0.70
  person_detection_threshold: 0.35
  violence_threshold: 0.85
  fire_threshold: 0.6
  vehicle_threshold: 0.4
  emergency_alert_policies: ["fire_detected_critical"]
  critical_alert_policies: ["fight_detected_critical", "crowd_policy_violation"]
  warning_alert_policies:
    [
      "restricted_access_sunday",
      "restricted_access_before_hours",
      "restricted_access_after_hours",
      "vehicle_crowd_policy_violation",
    ]

pipeline:
  width: 1920
  height: 1080

policy:
  crowd_controlled_zones: ["cafeteria", "reception_area", "boss_cabin"]
  boss_cabin:
    open_hour: 6
    close_hour: 7
    allowlist: ["sampad", "sagar"]
  office:
    open_hour: 4
    open_min: 0
    close_hour: 12
    close_min: 45

cameras:
  0:
    name: "reception_area"
    uri: "rtsp://admin:hik%402024@192.168.0.64:554/Streaming/Channels/101"
  1:
    name: "employee_area"
    uri: "rtsp://admin:hik%402024@192.168.0.65:554/Streaming/Channels/101"
  2:
    name: "boss_cabin"
    uri: "rtsp://admin:hik%402024@192.168.0.66:554/Streaming/Channels/101"
  3:
    name: "cafeteria"
    uri: "rtsp://admin:hik%402024@192.168.0.67:554/Streaming/Channels/101"